/**********************************************************************
 *
 *   Types file generated by Quest
 *
 *   Types for the components props go in this file
 *   To set up custom types for the components props, edit the corresponding types in this file
 *   Once you edit a type to no longer by "any", be careful to not override it on your next export
 *   Verify diff before merging
 *
 *   For help and further details refer to:
 *   https://docs.quest.ai/react/fundamentals/exporting-code
 *
 *
 **********************************************************************/






export interface Footer1Props {
  className?: any;
  metadata: any;
}




export interface Footer1Props {
  className?: any;
  metadata: any;
}



export interface SampleCardGridProps {
  className?: any;
}






export interface Card2Props {
  className?: any;
}






export interface BuildAreaManualBuildProps {
  className?: any;
  testvl: any;
  prop2: any;
}






export interface HandDrawn04Props {
  className?: any;
}







export interface Form2Props {
  className?: any;
}





export interface SampleCardProps {
  className?: any;
  metadata: any;
}






export interface DemoCardProps {
  className?: any;
  metadata: any;
}






export interface Frame96Props {
  className?: any;
}






export interface IconTimeProps {
  className?: any;
}






export interface IconCommitProps {
  className?: any;
}

export interface Footer1Props {
  className?: any;
  metadata: any;
}




export interface Footer1Props {
  className?: any;
  metadata: any;
}






export interface SampleCardGridProps {
  className?: any;
}







export interface Card2Props {
  className?: any;
}







export interface BuildAreaManualBuildProps {
  className?: any;
  testvl: any;
  prop2: any;
}







export interface HandDrawn04Props {
  className?: any;
}








export interface Form2Props {
  className?: any;
}






export interface SampleCardProps {
  className?: any;
  metadata: any;
}







export interface DemoCardProps {
  className?: any;
  metadata: any;
}







export interface Frame96Props {
  className?: any;
}







export interface IconTimeProps {
  className?: any;
}







export interface IconCommitProps {
  className?: any;
}
