/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { Frame96Props } from 'types';

const Frame961: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 10px 0px 166px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const ViewLogs: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(85, 103, 213, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  margin: `0px`,
}));

function Frame96(props: Frame96Props): JSX.Element {
  return (
    <Frame961 className={props.className}>
      <ViewLogs>{`View More`}</ViewLogs>
    </Frame961>
  );
}

export default Frame96;
