/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
const useCard2 = () => {
  const validateBookNow = () => {
    // Perform your validation logic here
    // For example, you can check if all the required fields are filled before allowing the user to book now

    // If validation passes, invoke the bookNow function from the fns object
    if (validationPasses) {
      fns.bookNow();
    } else {
      // Handle validation failure
    }
  };

  const data: any = {};

  const fns: any = { validateBookNow };

  return { data, fns };
};

export default useCard2;
