/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { SvgIcon } from '@mui/material';
import { styled } from '@mui/material/styles';
import IconTime from 'components/IconTime/IconTime';
import Button1 from 'components/Button1/Button1';
import Toggler from 'components/Toggler/Toggler';
import Checkbox1 from 'components/Checkbox1/Checkbox1';
import Label from 'components/Label/Label';
import IconCommit from 'components/IconCommit/IconCommit';
import Frame96 from 'components/Frame96/Frame96';
import { BuildAreaManualBuildProps } from 'types';

const BuildAreaManualBuild1: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(247, 248, 251, 1)`,
  border: `3px solid rgba(224, 226, 233, 1)`,
  boxSizing: `border-box`,
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 24px 24px 24px`,
  overflow: `hidden`,
  height: 'auto',
}));

const Frame94: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(247, 248, 251, 1)`,
  boxShadow: `inset 0px -1px 0px rgba(224, 226, 233, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `16px 0px`,
  boxSizing: `border-box`,
  width: `240px`,
  margin: `0px`,
}));

const BuildArea: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(64, 64, 75, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `500`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Frame86: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(85, 103, 213, 1)`,
  boxSizing: `border-box`,
  borderRadius: `6px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `flex-start`,
  padding: `12px 12px 11px 16px`,
  width: `240px`,
  margin: `16px 0px 0px 0px`,
});

const Frame85: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Id2312345UpdateHe: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(64, 64, 75, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame84: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `9px 0px 0px 0px`,
});

const IconTime1: any = styled(IconTime)(({ theme }: any) => ({
  width: `16px`,
  height: `16px`,
  margin: `0px`,
}));

const ByJaneSmithF2398W: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(64, 64, 75, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `0px 0px 0px 4px`,
}));

const IconGo: any = styled('img')({
  height: `auto`,
  width: `16px`,
  margin: `0px`,
});

const Frame93: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(224, 226, 233, 1)`,
  boxSizing: `border-box`,
  borderRadius: `6px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `16px`,
  width: `241px`,
  margin: `16px 0px 0px 0px`,
});

const Frame89: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Frame87: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Build: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 34, 40, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame88: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const IconEdit: any = styled('img')({
  height: `auto`,
  width: `16px`,
  margin: `0px`,
});

const Group66: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `32px`,
  width: `167px`,
  margin: `16px 0px 0px 0px`,
});

const RepositoryGitHubComBSpan1: any = styled('span')(({ theme }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(64, 64, 75, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
}));

const RepositoryGitHubComBSpan2: any = styled('span')(({ theme }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(141, 145, 163, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
}));

const RepositoryGitHubComB: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Id2312345UpdateHe1Span1: any = styled('span')(({ theme }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(64, 64, 75, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
}));

const Id2312345UpdateHe1Span2: any = styled('span')(({ theme }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(141, 145, 163, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
}));

const Id2312345UpdateHe1Span3: any = styled('span')(({ theme }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(64, 64, 75, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
}));

const Id2312345UpdateHe1Span4: any = styled('span')(({ theme }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(141, 145, 163, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
}));

const Id2312345UpdateHe1: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `16px 0px 0px 0px`,
}));

const ContextSpan1: any = styled('span')(({ theme }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(64, 64, 75, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
}));

const ContextSpan2: any = styled('span')(({ theme }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(141, 145, 163, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
}));

const Context: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `16px 0px 0px 0px`,
}));

const OpenApiFilepathDocsOSpan1: any = styled('span')(({ theme }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(64, 64, 75, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
}));

const OpenApiFilepathDocsOSpan2: any = styled('span')(({ theme }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(141, 145, 163, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
}));

const OpenApiFilepathDocsO: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `16px 0px 0px 0px`,
}));

const ManualDeploy: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `76px`,
  width: `240px`,
  margin: `16px 0px 0px 0px`,
});

const Button2: any = styled(Button1)(({ theme }: any) => ({
  width: `72px`,
  position: `absolute`,
  left: `1px`,
  top: `36px`,
}));

const Frame102: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `0px`,
});

const EnableAutoDeploy: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `24px`,
  width: `240px`,
  margin: `0px`,
});

const Toggler1: any = styled(Toggler)(({ theme }: any) => ({
  width: `29px`,
  height: `16px`,
  position: `absolute`,
  left: `211px`,
  top: `4px`,
}));

const Checkbox2: any = styled(Checkbox1)(({ theme }: any) => ({
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Main: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `237px`,
  margin: `12px 0px 0px 0px`,
});

const Left: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(85, 103, 213, 1)`,
  boxShadow: `0px 1px 2px rgba(0, 0, 0, 0.15)`,
  borderRadius: `5px 0px 0px 5px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `8px 24px`,
  boxSizing: `border-box`,
  width: `197px`,
  margin: `0px`,
}));

const IconAdd: any = styled('img')({
  height: `16px`,
  width: `16px`,
  margin: `0px 0px 0px 8px`,
});

const ConfigureDeploy: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Vector9: any = styled('img')({
  height: `40px`,
  width: `0px`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Right: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(85, 103, 213, 1)`,
  boxShadow: `0px 1px 2px rgba(0, 0, 0, 0.15)`,
  borderRadius: `0px 5px 5px 0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `12px`,
  boxSizing: `border-box`,
  margin: `0px`,
}));

const IconChevronDown: any = styled('img')({
  height: `auto`,
  width: `16px`,
  margin: `0px`,
});

const LatestDeployments: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 34, 40, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `500`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  margin: `16px 0px 0px 0px`,
}));

const RectangleCopy53: any = styled('div')(({ theme }: any) => ({
  opacity: `0.4302920401096344`,
  backgroundColor: `rgba(203, 206, 219, 1)`,
  height: `1px`,
  width: `240px`,
  margin: `16px 0px 0px 0px`,
}));

const Group90: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `65px`,
  width: `240px`,
  margin: `16px 0px 0px 0px`,
});

const Frame101: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `0px`,
});

const Group89: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `56px`,
  width: `237px`,
  margin: `0px`,
});

const Frame881: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `0px`,
});

const IconSuccessFilled: any = styled('img')({
  height: `auto`,
  width: `16px`,
  margin: `0px`,
});

const Frame100: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 9px`,
});

const DeployedToProdBy: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(64, 64, 75, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `500`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  height: `33px`,
  width: `128px`,
  margin: `0px`,
});

const Group88: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `16px`,
  width: `75px`,
  margin: `5px 0px 0px 0px`,
});

const DeployedToProdBy1: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(141, 145, 163, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  position: `absolute`,
  left: `20px`,
  top: `0px`,
}));

const IconCommit1: any = styled('img')({
  height: `auto`,
  width: `16px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group76: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `75px`,
  height: `56px`,
  margin: `0px 0px 0px 9px`,
});

const Frame99: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `75px`,
  left: `0px`,
  top: `0px`,
});

const Frame98: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const IconTime2: any = styled(IconTime)(({ theme }: any) => ({
  width: `16px`,
  height: `16px`,
  margin: `0px`,
}));

const ByJaneSmithF2398W1: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(64, 64, 75, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `0px 0px 0px 6px`,
}));

const Label1: any = styled(Label)(({ theme }: any) => ({
  margin: `2px 0px 0px 0px`,
}));

const ViewLogs: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(85, 103, 213, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  margin: `2px 0px 0px 0px`,
}));

const RectangleCopy54: any = styled('div')(({ theme }: any) => ({
  opacity: `0.4302920401096344`,
  backgroundColor: `rgba(203, 206, 219, 1)`,
  height: `1px`,
  width: `240px`,
  margin: `8px 0px 0px 0px`,
}));

const Group91: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `65px`,
  width: `240px`,
  margin: `16px 0px 0px 0px`,
});

const Frame1011: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `0px`,
});

const Group891: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `56px`,
  width: `237px`,
  margin: `0px`,
});

const Frame882: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `0px`,
});

const FilledProgress: any = styled('img')({
  height: `auto`,
  width: `16px`,
  margin: `0px`,
});

const Frame1001: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 9px`,
});

const DeployedToProdBy2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(64, 64, 75, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `500`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  height: `33px`,
  width: `128px`,
  margin: `0px`,
});

const Group881: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `16px`,
  width: `75px`,
  margin: `5px 0px 0px 0px`,
});

const DeployedToProdBy3: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(141, 145, 163, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  position: `absolute`,
  left: `20px`,
  top: `0px`,
}));

const IconCommit2: any = styled(IconCommit)(({ theme }: any) => ({
  width: `16px`,
  height: `16px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Group761: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `75px`,
  height: `56px`,
  margin: `0px 0px 0px 9px`,
});

const Frame991: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `75px`,
  left: `0px`,
  top: `0px`,
});

const Frame981: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const IconTime3: any = styled(IconTime)(({ theme }: any) => ({
  width: `16px`,
  height: `16px`,
  margin: `0px`,
}));

const ByJaneSmithF2398W2: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(64, 64, 75, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `0px 0px 0px 6px`,
}));

const Label2: any = styled(Label)(({ theme }: any) => ({
  margin: `2px 0px 0px 0px`,
}));

const ViewLogs1: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(85, 103, 213, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  margin: `2px 0px 0px 0px`,
}));

const RectangleCopy541: any = styled('div')(({ theme }: any) => ({
  opacity: `0.4302920401096344`,
  backgroundColor: `rgba(203, 206, 219, 1)`,
  height: `1px`,
  width: `240px`,
  margin: `8px 0px 0px 0px`,
}));

const Group92: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `65px`,
  width: `240px`,
  margin: `16px 0px 0px 0px`,
});

const Frame1012: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `0px`,
});

const Group892: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `56px`,
  width: `237px`,
  margin: `0px`,
});

const Frame883: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `0px`,
});

const IconErrorFilled: any = styled('img')({
  height: `auto`,
  width: `16px`,
  margin: `0px`,
});

const Frame1002: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 9px`,
});

const DeployedToProdBy4: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(64, 64, 75, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `500`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  height: `33px`,
  width: `128px`,
  margin: `0px`,
});

const Group882: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `16px`,
  width: `75px`,
  margin: `5px 0px 0px 0px`,
});

const DeployedToProdBy5: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(141, 145, 163, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  position: `absolute`,
  left: `20px`,
  top: `0px`,
}));

const IconCommit3: any = styled(IconCommit)(({ theme }: any) => ({
  width: `16px`,
  height: `16px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Group762: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `75px`,
  height: `56px`,
  margin: `0px 0px 0px 9px`,
});

const Frame992: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `75px`,
  left: `0px`,
  top: `0px`,
});

const Frame982: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const IconTime4: any = styled(IconTime)(({ theme }: any) => ({
  width: `16px`,
  height: `16px`,
  margin: `0px`,
}));

const ByJaneSmithF2398W3: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(64, 64, 75, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `0px 0px 0px 6px`,
}));

const Label3: any = styled(Label)(({ theme }: any) => ({
  margin: `2px 0px 0px 0px`,
}));

const ViewLogs2: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(85, 103, 213, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gilmer`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  margin: `2px 0px 0px 0px`,
}));

const RectangleCopy542: any = styled('div')(({ theme }: any) => ({
  opacity: `0.4302920401096344`,
  backgroundColor: `rgba(203, 206, 219, 1)`,
  height: `1px`,
  width: `240px`,
  margin: `8px 0px 0px 0px`,
}));

const Frame961: any = styled(Frame96)(({ theme }: any) => ({
  margin: `16px 0px 0px 0px`,
}));

function BuildAreaManualBuild(props: BuildAreaManualBuildProps): JSX.Element {
  return (
    <BuildAreaManualBuild1 className={props.className}>
      <Frame94>
        <BuildArea>{`Build Area`}</BuildArea>
      </Frame94>
      <Frame86>
        <Frame85>
          <Id2312345UpdateHe>{`ID 2312345`}</Id2312345UpdateHe>
          <Frame84>
            <IconTime1 />
            <ByJaneSmithF2398W>{`2 min ago`}</ByJaneSmithF2398W>
          </Frame84>
        </Frame85>
        <IconGo
          src={`assets/images/BuildAreaManualBuild_Icon_Go.svg`}
          loading="lazy"
          alt={'Icon/Go'}
        />
      </Frame86>
      <Frame93>
        <Frame89>
          <Frame87>
            <Build>{`Build Configurations`}</Build>
          </Frame87>
          <Frame88>
            <IconEdit
              src={`assets/images/BuildAreaManualBuild_Icon_Edit.svg`}
              loading="lazy"
              alt={'Icon/Edit'}
            />
          </Frame88>
        </Frame89>
        <Group66>
          <RepositoryGitHubComB>
            <RepositoryGitHubComBSpan1>{`Repository:
`}</RepositoryGitHubComBSpan1>
            <RepositoryGitHubComBSpan2>{`GitHub.com/bgx/byoc-node `}</RepositoryGitHubComBSpan2>
          </RepositoryGitHubComB>
        </Group66>
        <Id2312345UpdateHe1>
          <Id2312345UpdateHe1Span1>{`Dockerfile`}</Id2312345UpdateHe1Span1>
          <Id2312345UpdateHe1Span2>{`:`}</Id2312345UpdateHe1Span2>
          <Id2312345UpdateHe1Span3>{` `}</Id2312345UpdateHe1Span3>
          <Id2312345UpdateHe1Span4>{`Dockerfile`}</Id2312345UpdateHe1Span4>
        </Id2312345UpdateHe1>
        <Context>
          <ContextSpan1>{`Context: `}</ContextSpan1>
          <ContextSpan2>{`.`}</ContextSpan2>
        </Context>
        <OpenApiFilepathDocsO>
          <OpenApiFilepathDocsOSpan1>{`OpenAPI filepath :
`}</OpenApiFilepathDocsOSpan1>
          <OpenApiFilepathDocsOSpan2>{`docs/open_api_definition.json`}</OpenApiFilepathDocsOSpan2>
        </OpenApiFilepathDocsO>
      </Frame93>
      <ManualDeploy>
        <Button2 />
        <Frame102>
          <EnableAutoDeploy>
            <Toggler1 />
            <Checkbox2 />
          </EnableAutoDeploy>
          <Main>
            <Left>
              {false && (
                <IconAdd
                  src={`assets/images/BuildAreaManualBuild_Icon_Add.png`}
                  loading="lazy"
                  alt={'Icon/Add'}
                />
              )}
              <ConfigureDeploy>{`Configure & Deploy`}</ConfigureDeploy>
            </Left>
            <Vector9
              src={`assets/images/BuildAreaManualBuild_Vector_9.png`}
              loading="lazy"
              alt={'Vector 9'}
            />
            <Right>
              <IconChevronDown
                src={`assets/images/BuildAreaManualBuild_Icon_Chevron_Down.svg`}
                loading="lazy"
                alt={'Icon/Chevron Down'}
              />
            </Right>
          </Main>
        </Frame102>
      </ManualDeploy>
      <LatestDeployments>{`Build History`}</LatestDeployments>
      <RectangleCopy53></RectangleCopy53>
      <Group90>
        <Frame101>
          <Group89>
            <Frame881>
              <IconSuccessFilled
                src={`assets/images/BuildAreaManualBuild_Icon_Success_filled.svg`}
                loading="lazy"
                alt={'Icon/Success filled'}
              />
              <Frame100>
                <DeployedToProdBy>
                  {`Deployed to Development
`}
                </DeployedToProdBy>
                <Group88>
                  <DeployedToProdBy1>{`#2312345`}</DeployedToProdBy1>
                  <IconCommit1
                    src={`assets/images/BuildAreaManualBuild_Icon_Commit.svg`}
                    loading="lazy"
                    alt={'Icon/Commit'}
                  />
                </Group88>
              </Frame100>
              <Group76>
                <Frame99>
                  <Frame98>
                    <IconTime2 />
                    <ByJaneSmithF2398W1>{`2 sec ago`}</ByJaneSmithF2398W1>
                  </Frame98>
                  <Label1 />
                  <ViewLogs>{`View Log`}</ViewLogs>
                </Frame99>
              </Group76>
            </Frame881>
          </Group89>
          <RectangleCopy54></RectangleCopy54>
        </Frame101>
      </Group90>
      <Group91>
        <Frame1011>
          <Group891>
            <Frame882>
              <FilledProgress
                src={`assets/images/BuildAreaManualBuild_Filled_Progress.svg`}
                loading="lazy"
                alt={'Filled/Progress'}
              />
              <Frame1001>
                <DeployedToProdBy2>
                  {`Development
In Progress
`}
                </DeployedToProdBy2>
                <Group881>
                  <DeployedToProdBy3>{`#2312345`}</DeployedToProdBy3>
                  <IconCommit2 />
                </Group881>
              </Frame1001>
              <Group761>
                <Frame991>
                  <Frame981>
                    <IconTime3 />
                    <ByJaneSmithF2398W2>{`3 hrs ago`}</ByJaneSmithF2398W2>
                  </Frame981>
                  <Label2 />
                  <ViewLogs1>{`View Log`}</ViewLogs1>
                </Frame991>
              </Group761>
            </Frame882>
          </Group891>
          <RectangleCopy541></RectangleCopy541>
        </Frame1011>
      </Group91>
      <Group92>
        <Frame1012>
          <Group892>
            <Frame883>
              <IconErrorFilled
                src={`assets/images/BuildAreaManualBuild_Icon_Error_Filled.svg`}
                loading="lazy"
                alt={'Icon/Error Filled'}
              />
              <Frame1002>
                <DeployedToProdBy4>
                  {`Development
Failed`}
                </DeployedToProdBy4>
                <Group882>
                  <DeployedToProdBy5>{`#2312345`}</DeployedToProdBy5>
                  <IconCommit3 />
                </Group882>
              </Frame1002>
              <Group762>
                <Frame992>
                  <Frame982>
                    <IconTime4 />
                    <ByJaneSmithF2398W3>{`5 hrs ago`}</ByJaneSmithF2398W3>
                  </Frame982>
                  <Label3 />
                  <ViewLogs2>{`View Log`}</ViewLogs2>
                </Frame992>
              </Group762>
            </Frame883>
          </Group892>
          <RectangleCopy542></RectangleCopy542>
        </Frame1012>
      </Group92>
      <Frame961 />
    </BuildAreaManualBuild1>
  );
}

export default BuildAreaManualBuild;
