/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { IconTimeProps } from 'types';

const IconTime1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `16px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const CombinedShape: any = styled('img')({
  height: `16px`,
  width: `16px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

function IconTime(props: IconTimeProps): JSX.Element {
  return (
    <IconTime1 className={props.className}>
      <CombinedShape
        src={`assets/images/IconTime_Combined_Shape.png`}
        loading="lazy"
        alt={'Combined Shape'}
      />
    </IconTime1>
  );
}

export default IconTime;
