/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { SampleCardProps } from 'types';
const useSampleCard = (props: SampleCardProps) => {
  const [data, setData] = React.useState({});

  const handleButtonClick = () => {
    window.open('https://www.external-site.com', '_blank');
  };
  const switchStateToTypeQuest = (
    duration = 0,
    delay = 0,
    easing = 'linear'
  ) => {
    // code to switch state
  };
  const switchStateToTypeQuest = (
    // code to switch state
  ) => {
    duration = 10,
    delay = 10,
    easing = 'linear'
  };

  const data: any = { data };

  const fns: any = {
    handleButtonClick,
    switchStateToTypeQuest,
    switchStateToTypeQuest,
  };

  return { data, fns };
};

export default useSampleCard;
